package config;

public class SimulationParams {
    public static final int WIDTH = 100;
    public static final int HEIGHT = 20;
    public static final int TICK_DURATION_MS = 1000;
    public static final int MAX_PLANTS_PER_CELL = 10;
    public static final int MAX_TOTAL_PLANTS = 2000;
    public static final int INITIAL_WOLVES = 5;
    public static final int INITIAL_RABBITS = 50;
    public static final int INITIAL_DUCKS = 30;
    public static final int INITIAL_CATERPILLARS = 100;
    public static final int INITIAL_BOAS = 5;
    public static final int INITIAL_FOXES = 10;
    public static final int INITIAL_BEARS = 2;
    public static final int INITIAL_EAGLES = 5;
    public static final int INITIAL_HORSES = 5;
    public static final int INITIAL_DEERS = 10;
    public static final int INITIAL_MICE = 100;
    public static final int INITIAL_GOATS = 20;
    public static final int INITIAL_SHEEP = 20;
    public static final int INITIAL_BOARS = 10;
    public static final int INITIAL_BUFFALOS = 5;
    public static final int MAX_WOLVES = 50;
    public static final int MAX_RABBITS = 500;
    public static final int MAX_DUCKS = 300;
    public static final int MAX_CATERPILLARS = 2000;
    public static final int MAX_BOAS = 50;
    public static final int MAX_FOXES = 50;
    public static final int MAX_BEARS = 10;
    public static final int MAX_EAGLES = 50;
    public static final int MAX_HORSES = 50;
    public static final int MAX_DEERS = 50;
    public static final int MAX_MICE = 1000;
    public static final int MAX_GOATS = 200;
    public static final int MAX_SHEEP = 200;
    public static final int MAX_BOARS = 100;
    public static final int MAX_BUFFALOS = 20;
    public static final int INITIAL_PLANTS = 500;
    public static final int SIMULATION_END_CONDITION = 0;
}